[build]
  command = "echo 'Building VoidSEO...'"
  functions = "netlify/functions"
  publish = "."

[functions]
  python_runtime = "3.9"

# Redirects for PAA Explorer app
[[redirects]]
  from = "/app/paa-explorer"
  to = "/apps/paa-explorer-app/index.html"
  status = 200

[[redirects]]
  from = "/app/paa-explorer/*"
  to = "/apps/paa-explorer-app/:splat"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
