[build]
  command = "echo 'Building PAA Explorer App...'"
  functions = "netlify/functions"
  publish = "."

[functions]
  python_runtime = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
